export const PROFILE = {
  name: "Komal ❤️",
  image: "/assets/komal_hero_solo.jpg",
};

export const HERO = {
  backgroundSrc: "/thumb/main.png",
  backgroundMobileSrc: "/thumb/mainph.png",
  videoSrc: "/videos/main.mp4",
  videoThumbnail: "/thumb/img1.png",
  badgeLabel: "Original Series",
  title: "Komal &\nKushagra",
  match: "100% Match",
  year: "2026",
  duration: "Lifetime",
  quality: "4K Ultra",
  ageRating: "U/A 13+",
  description:
    "A legendary romantic story of two souls meeting on 14th December 2025, falling in love over movies, metro rides, chocolates, and infinite talks, building a forever together.",
};

export const ROWS = [
  {
    id: "row-popular",
    rowTitle: "Popular on Komal's Netflix 🍿",
    items: [
      {
        id: "p1",
        title: "Our Roka Day 💍",
        img: "/assets/roka_together.jpg",
        videoSrc: "/videos/v7.mp4",
        tags: ["Dec 14, 2025", "First Meeting"],
        match: "100% Match",
        age: "U/A",
        duration: "Forever",
        desc: "The very first day we met... the peacock feather on the blazer, the sweet smiles, and the beginning of our forever story.",
      },
      {
        id: "p2",
        title: "First Meeting & Raja Saab 🍫🎬",
        img: "/assets/komal_solo_2.jpg",
        videoSrc: "/videos/v6.mp4",
        tags: ["Metro Pickup", "Raja Saab"],
        match: "99% Match",
        age: "U/A",
        duration: "Full Day",
        desc: "You picked me up from the metro, shared chocolates, watched Raja Saab together, and turned a simple day into our first priceless memory.",
      },
      {
        id: "p3",
        title: "Third Meeting & Govardhan Parikrama 🛕",
        img: "/assets/meeting3.jpg",
        videoSrc: "/videos/v5.mp4",
        tags: ["May 16, 2026", "Barsana & Govardhan"],
        match: "100% Match",
        age: "U/A",
        duration: "Full Day",
        desc: "Krishnavataram movie, McDonald's, visiting Raman Reti, Ladli Ji (Barsana), and completing Govardhan Parikrama together. A day full of memories and togetherness.",
      },
      {
        id: "p4",
        title: 'Office Surprise & "Hello, Mrs. Komal" 🎁',
        img: "/assets/meeting4.jpg",
        videoSrc: "/videos/v4.mp4",
        tags: ["July 22, 2026", "Office Surprise"],
        match: "100% Match",
        age: "U/A",
        duration: "Unforgettable",
        desc: 'Surprising Komal outside her office, seeing her completely shocked expression, fast heartbeat, and whispering "Hello, Mrs. Komal."',
      },
      {
        id: "p5",
        title: "Unannounced Visit & Awarapan 2 ✨",
        img: "/assets/meeting5.jpg",
        videoSrc: "/videos/v3.mp4",
        tags: ["Aug 29, 2026", "Awarapan 2"],
        match: "100% Match",
        age: "U/A",
        duration: "Memorable",
        desc: "Another unannounced surprise visit outside office, watching Awarapan 2 together, and turning an ordinary day into a beautiful memory.",
      },
    ],
  },
  {
    id: "row-trending",
    rowTitle: "Trending Episodes 💖",
    items: [
      {
        id: "t1",
        title: "Special Birthday Wishes 🎂",
        img: "/assets/komal_solo_5.jpg",
        videoSrc: "/videos/v2.mp4",
        tags: ["Celebration", "Feel-Good"],
        match: "100% Match",
        age: "U/A",
        duration: "Special",
        desc: "Wishing the most beautiful person in the world a birthday as bright and lovely as her smile!",
      },
      {
        id: "t2",
        title: "Future Milestones 🥂",
        img: "/assets/roka_family.jpg",
        videoSrc: "/videos/v1.mp4",
        tags: ["Family Blessings", "Together"],
        match: "100% Match",
        age: "U/A",
        duration: "Lifetime",
        desc: "Surrounded by family blessings and love, walking hand in hand into a future filled with happiness.",
      },
      {
        id: "t3",
        title: "Second Meeting & College Certificate 📜",
        img: "/assets/meeting2.jpg",
        videoSrc: "/videos/v6.mp4",
        tags: ["Mar 5, 2026", "Mall & College"],
        match: "100% Match",
        age: "U/A",
        duration: "Full Day",
        desc: "Watched The Kerala Story 2 at the mall, collected college certificates together outside college.",
      },
    ],
  },
];
